import Head from "next/head";

import styles from "@/styles/login.module.scss";
import LogoImg from "@/assets/codeleap_logo.png";
import Image from "next/image";
import router from "next/router";

import { FaUserCircle } from 'react-icons/fa';

export default function Login() {
  const handleLogin = async () => {
    router.push('/home');
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={styles.container}>
        <Image src={LogoImg} alt="Logo" />
        <form>
          <header>
            <strong>Welcome to CodeLeap!</strong>
          </header>

          <div className={styles.formInputs}>
            <div>
              <FaUserCircle />
              <input placeholder="Please enter your username"/>
            </div>
          </div>

          <div className={styles.formButtons}>
            <button type="button" onClick={handleLogin}>
              <span>LOGIN</span>
            </button>
          </div>
        </form>
      </main>
    </>
  )
}