import Head from "next/head";

import styles from "@/styles/login.module.scss";
import LogoImg from "@/assets/codeleap_logo.png";
import Image from "next/image";
import router from "next/router";

import { FaUserCircle } from 'react-icons/fa';

import { useForm } from "react-hook-form";
import { useAuth } from "@/contexts/AuthProvider";

interface IFormValues {
  username: string;
}

export default function Login() {
  const { authenticate } = useAuth();

  const {
    register,
    handleSubmit,
    formState: { errors }
  } = useForm<IFormValues>();

  const handleLogin = async ({ username }: IFormValues ) => {
    try {
      await authenticate(username);
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={styles.container}>
        <Image src={LogoImg} alt="Logo" />
        <form onSubmit={handleSubmit(handleLogin)}>
          <header>
            <strong>Welcome to CodeLeap!</strong>
          </header>

          <div className={styles.formInputs}>
            <div>
              <FaUserCircle />
              <input
                {...register('username')}
                placeholder="Please enter your username"
              />
              {errors.username && (
                <span>{errors.username.message}</span>
              )}
            </div>
          </div>

          <div className={styles.formButtons}>
            <button>
              <span>LOGIN</span>
            </button>
          </div>
        </form>
      </main>
    </>
  )
}