import Head from "next/head";
import { FaEdit, FaTrash } from "react-icons/fa";

import styles from '@/styles/home.module.scss';

export default function Home () {
  return (
    <>
      <Head>
        <title>Home - CodeLeap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className={styles.container}>
        <div>
          <header>
            <label>CodeLeap Network</label>
          </header>

          <form>
            <span>What&apos;s on yout mind</span>

            <div className={styles.formInputs}>
              <div>
                <input placeholder="title" />
              </div>

              <div>
                <textarea placeholder="content here" />
              </div>
            </div>

            <div className={styles.formButtons}>
              <button>
                <span>Create</span>
              </button>
            </div>
          </form>

          <div>
            <div>
              <header>
                <label>My first post at codeleap network</label>

                <div>
                  <FaTrash />

                  <FaEdit />
                </div>
              </header>

              <div>
                <div>
                  <span>@victor</span>

                  <span>25 minute ago</span>
                </div>

                <p>
                  Curabitur suscipit suscipit tellus. Phasellus consectetuer vestibulum elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas egestas arcu quis ligula mattis placerat. Duis vel nibh at velit scelerisque suscipit.

                  Duis lobortis massa imperdiet quam. Aenean posuere, tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus. Fusce a quam. Nullam vel sem. Nullam cursus lacinia erat.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}